### ISSUE TITLE
"Error executing query: not an error" printed in console on each operation.

### ISSUE THREAD

**Issue by LeoBlanchette** [2shady4u/godot-sqlite#199]
I'm sure this is my ignorance. 
This prints to console every time an operation is done, and (apparently) does not contain an error: 

**Error executing query: not an error**

For large operations, this prints thousands of times. 

How can I remove this?

**Comment by 2shady4u** [comment]
Hello @LeoBlanchette,

Could you provide additional information? 
Could you provide some way to replicate the issue on my side?

**Comment by CavemanIke** [comment]
Just ran into this. I was wondering why a part of my code was not executing correctly, because I was checking for the existence of an error message. I discovered that it returns "not an error" which runs contrary to the documentation:

> Contains the zErrMsg returned by the SQLite query in human-readable form. An empty string corresponds with the case in which the query executed succesfully.

**Comment by 2shady4u** [comment]
> Just ran into this. I was wondering why a part of my code was not executing correctly, because I was checking for the existence of an error message. I discovered that it returns "not an error" which runs contrary to the documentation:
> 
> > Contains the zErrMsg returned by the SQLite query in human-readable form. An empty string corresponds with the case in which the query executed succesfully.

Fixed in 74d7e7e9ee85f7919416a39ea7bdc9f139797593
Now the error message property always returns an empty string if there is no error.

**Comment by Gren4** [comment]
> Fixed in [74d7e7e](https://github.com/2shady4u/godot-sqlite/commit/74d7e7e9ee85f7919416a39ea7bdc9f139797593) Now the error message property always returns an empty string if there is no error.

Hi, i still get the "not an error" string. 
Tried on Godot 4.7.2, SQLite v4.9, Windows 11.

**Comment by 2shady4u** [comment]
> > Fixed in [74d7e7e](https://github.com/2shady4u/godot-sqlite/commit/74d7e7e9ee85f7919416a39ea7bdc9f139797593) Now the error message property always returns an empty string if there is no error.
> 
> Hi, i still get the "not an error" string. Tried on Godot 4.7.2, SQLite v4.9, Windows 11.

Hello, could you give some more information?
According to the code the error_message should be empty if there is no error:
```cpp
void SQLite::update_error_message(int rc) {
	/* The 'sqlite3_errmsg()'-method returns a non-empty string when rc is equal to SQLITE_OK, SQLITE_ROW or SQLITE_DONE. */
	/* However, setting the message to an empty string makes much more sense. */
	if (rc == SQLITE_OK || rc == SQLITE_ROW || rc == SQLITE_DONE) {
		error_message = "";
	}
	const char *zErrMsg = sqlite3_errmsg(db);
	error_message = String::utf8(zErrMsg);
}
```

**Comment by 2shady4u** [comment]
I just tested it and you are correct @Gren4 !
Seems like I forgot add a return here 😫 

```cpp
void SQLite::update_error_message(int rc) {
	/* The 'sqlite3_errmsg()'-method returns a non-empty string when rc is equal to SQLITE_OK, SQLITE_ROW or SQLITE_DONE. */
	/* However, setting the message to an empty string makes much more sense. */
	if (rc == SQLITE_OK || rc == SQLITE_ROW || rc == SQLITE_DONE) {
		error_message = "";
		return;
	}
	const char *zErrMsg = sqlite3_errmsg(db);
	error_message = String::utf8(zErrMsg);
}
```

**Comment by 2shady4u** [comment]
Should now be fixed (for real) in 1e432b3b03eac186351a8f482226654e1ccd0ce3

**Comment by Gren4** [comment]
> Should now be fixed (for real) in [1e432b3](https://github.com/2shady4u/godot-sqlite/commit/1e432b3b03eac186351a8f482226654e1ccd0ce3)

Great, thank you!
