### ISSUE TITLE
iOS: Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by vanoak** [2shady4u/godot-sqlite#69]
**Environment:**
 - OS: macOs 11.6.3 -> iOS 12.5.5 (Xcode 13.2.1)
 - Godot version: 3.4.2
 - _godot-sqlite_ version: 3.0

**Issue description:**
Error in compilation

**Steps to reproduce:**
1. Make a new project
2. Export with version iOS template (project succeeds)
3. Add sqlite plugin; enable it
4. Export again (should not compile returning the error in the title). 

**Minimal reproduction project:**

**Additional context**

**Comment by 2shady4u** [comment]
> **Environment:**
> 
>     * OS: macOs 11.6.3 -> iOS 12.5.5 (Xcode 13.2.1)
> 
>     * Godot version: 3.4.2
> 
>     * _godot-sqlite_ version: 3.0
> 
> 
> **Issue description:** Error in compilation
> 
> **Steps to reproduce:**
> 
>     1. Make a new project
> 
>     2. Export with version iOS template (project succeeds)
> 
>     3. Add sqlite plugin; enable it
> 
>     4. Export again (should not compile returning the error in the title).
> 
> 
> **Minimal reproduction project:**
> 
> **Additional context**

Hi @vanoak !

This should be fixed in the latest release (3.1) which you can either get from the Asset Lib or download in this repository's Releases. 
Important to note is that you have to explicitly add the godot-cpp static binaries in your XCode project as described here:
https://github.com/2shady4u/godot-sqlite#6-how-to-export-to-ios-using-xcode

https://github.com/2shady4u/godot-sqlite#6-how-to-export-to-ios-using-xcode

**Comment by vanoak** [comment]
HI @2shady4u,

I deleted the 3.0 version and downloaded the 3.1 but the error still occurs. Is there a tmp or .import file that could be on cache?

As a side note, in the source code the armv7 and arm64 static libraries are actually in the wrong folders - the armv7 in the arm64 and vic-versa.  Didn't get to that step of including them on Xcode.

**Comment by 2shady4u** [comment]
@vanoak Due to an unfortunate copy-paste mistake, the arm64 and armv7 are indeed swapped.

When exporting to arm64 you should include the relevant godot bindings for arm64 (as found in the armv7 due to this mistake).

This older closed issue might be useful for you:

**Comment by vanoak** [comment]
Hi @2shady4u,

I confirm that after changing the files to their correct folder, exporting works without an issue. 

Also, my tests were saving a database to the user:// folder, creating a table, inserting data, retrieving the same data. The second time, database already existed so it just inserted another row and retrieved alll data from the table.

Worked without an issue.

Thank you!

**Comment by 2shady4u** [comment]
Great to hear that it is working 🥳 

If there's any other issues, please feel free to open another issue.
